services:

  nginx:
    image: nginx:1.23
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs/fastcgi_params:/etc/nginx/fastcgi_params:ro
      - ./ssl/letsencrypt/:/etc/letsencrypt/:ro
      - ./sites/:/sites/:ro

