services:

  nginx:
    image: nginx:1.23
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php
      - node
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs/fastcgi_params:/etc/nginx/fastcgi_params:ro
      - ./configs/ssl/letsencrypt/:/etc/letsencrypt/:ro
      - ./sites/:/sites/:ro

  php:
    image: ihor16/php-mysqli:8.2-fpm
    volumes:
      - ./sites/video-platform/app/:/sites/video-platform/app/:ro

  node:
    image: node:18
    command: >
      sh -c "cd /sites/ubc-explorer/ &&
             yarn install &&
             yarn start"
    volumes:
      - ./sites/ubc-explorer/:/sites/ubc-explorer/

